"""empty message

Revision ID: 3f9ebce0b640
Revises: 
Create Date: 2022-08-26 10:23:31.056801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f9ebce0b640'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('Invoice Number', sa.String(length=255), nullable=False),
    sa.Column('Invoice Currency', sa.String(length=255), nullable=False),
    sa.Column('Invoice Amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('Invoice Country', sa.String(length=255), nullable=True),
    sa.Column('Enabled', sa.Boolean(), nullable=True),
    sa.Column('Date Added', sa.DateTime(), nullable=True),
    sa.Column('Date Modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_Enabled'), 'invoice', ['Enabled'], unique=False)
    op.create_index(op.f('ix_invoice_Invoice Amount'), 'invoice', ['Invoice Amount'], unique=False)
    op.create_index(op.f('ix_invoice_Invoice Country'), 'invoice', ['Invoice Country'], unique=False)
    op.create_index(op.f('ix_invoice_Invoice Currency'), 'invoice', ['Invoice Currency'], unique=False)
    op.create_index(op.f('ix_invoice_Invoice Number'), 'invoice', ['Invoice Number'], unique=True)
    op.create_index(op.f('ix_invoice_user'), 'invoice', ['user'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_user'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_Invoice Number'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_Invoice Currency'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_Invoice Country'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_Invoice Amount'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_Enabled'), table_name='invoice')
    op.drop_table('invoice')
    # ### end Alembic commands ###
