"""empty message

Revision ID: 3b762fe209c3
Revises: 
Create Date: 2022-08-26 10:22:01.092445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b762fe209c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('Password', sa.String(length=128), nullable=True),
    sa.Column('Name', sa.String(length=256), nullable=True),
    sa.Column('Enabled', sa.Boolean(), nullable=True),
    sa.Column('Date Added', sa.DateTime(), nullable=True),
    sa.Column('Date Modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_Email'), 'user', ['Email'], unique=True)
    op.create_index(op.f('ix_user_Enabled'), 'user', ['Enabled'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_Enabled'), table_name='user')
    op.drop_index(op.f('ix_user_Email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
